#
version: "3"
services:
  database:
    image: "registry.redhat.io/rhel8/postgresql-13:1-21"
    container_name: "match-database"
    environment:
      - POSTGRESQL_USER=devuser1
      - POSTGRESQL_PASSWORD=devuser1
      - POSTGRESQL_DATABASE=matcher
      - POSTGRES_ADMIN_PASSWORD=mrfred1
    ports:
      - "5432:5432"
#    volumes:
#      - ./db-init/initialize-databases.sql:/docker-entrypoint-initdb.d/init.sql
  monitoring:
    image: "prom/prometheus:v2.30.1"
    container_name: "match-monitoring"
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
